common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *common
  host: localhost
  database: boo_development

test:
  <<: *common
  host: localhost
  database: boo_test

production:
  <<: *common
  url: <%= ENV['DATABASE_URL'] %>
